services:
  api:
    build: .
    container_name: backend

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17

    container_name: postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: labourbaba

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: redis

    ports:
      - "6379:6379"

volumes:
  postgres_data:
